"""Analyze historical draft tendencies from 2024-2025 drafts."""

# Known closers (manually tagged from the draft data)
CLOSERS_2025 = {
    "Emmanuel Clase", "Devin Williams", "Josh Hader", "Edwin Díaz",
    "Raisel Iglesias", "Mason Miller", "Ryan Helsley", "Ryan Walker",
    "Andrés Muñoz", "Jhoan Duran", "Robert Suarez", "Félix Bautista",
    "Tanner Scott", "Pete Fairbanks", "Kenley Jansen", "Aroldis Chapman",
    "Clay Holmes", "David Bednar", "Jordan Romano",
}
CLOSERS_2024 = {
    "Emmanuel Clase", "Edwin Díaz", "Josh Hader", "Raisel Iglesias",
    "Andrés Muñoz", "Alexis Díaz", "Ryan Helsley", "David Bednar",
    "Clay Holmes", "Pete Fairbanks", "Craig Kimbrel", "Kenley Jansen",
    "Tanner Scott", "Paul Sewald", "Jordan Romano", "José Alvarado",
    "Robert Suarez", "Kyle Finnegan", "Carlos Estévez", "Mason Miller",
    "Jhoan Duran", "Hunter Harvey", "José Leclerc", "Alex Lange",
    "Evan Phillips", "Camilo Doval",
}

# Pitchers (SP) - not closers
PITCHERS_2025 = {
    "Paul Skenes", "Tarik Skubal", "Zack Wheeler", "Logan Gilbert",
    "Garrett Crochet", "Chris Sale", "Corbin Burnes", "Cole Ragans",
    "Tyler Glasnow", "Yoshinobu Yamamoto", "Framber Valdez", "Dylan Cease",
    "Blake Snell", "Jacob deGrom", "Spencer Schwellenbach", "Pablo López",
    "Shota Imanaga", "Logan Webb", "Aaron Nola", "Tanner Bibee",
    "Max Fried", "Freddy Peralta", "Bailey Ober", "Hunter Brown",
    "Luis Castillo", "Joe Ryan", "Bryce Miller", "Hunter Greene",
    "Roki Sasaki", "Zac Gallen", "George Kirby", "Spencer Strider",
    "Sandy Alcantara", "Justin Steele", "Sonny Gray", "Jack Flaherty",
    "Kevin Gausman", "Cristopher Sánchez", "Jeff Hoffman",
    "Shane McClanahan", "Yusei Kikuchi", "Gavin Williams", "Shane Baz",
    "Bryan Woo", "Carlos Rodón", "Nick Pivetta", "Ryan Pepiot",
    "Seth Lugo", "Robbie Ray", "Taj Bradley", "Brandon Pfaadt",
    "Zach Eflin", "MacKenzie Gore", "Nick Lodolo", "Tanner Houck",
    "Mitch Keller", "Kodai Senga", "Reynaldo López",
}
PITCHERS_2024 = {
    "Corbin Burnes", "Spencer Strider", "Gerrit Cole", "Zac Gallen",
    "Zack Wheeler", "Tyler Glasnow", "Freddy Peralta", "Aaron Nola",
    "Framber Valdez", "Logan Gilbert", "Kevin Gausman", "Logan Webb",
    "Yoshinobu Yamamoto", "George Kirby", "Luis Castillo", "Cole Ragans",
    "Chris Bassitt", "Justin Steele", "Blake Snell", "Bobby Miller",
    "Zach Eflin", "Tanner Bibee", "Hunter Brown", "Grayson Rodriguez",
    "Joe Ryan", "Dylan Cease", "Pablo López", "Max Fried", "Bailey Ober",
    "Shota Imanaga", "Ryan Pepiot", "Sonny Gray", "Hunter Greene",
    "Bryce Miller", "Michael King", "Cristian Javier", "Nick Pivetta",
    "Mitch Keller", "Nathan Eovaldi", "Carlos Rodón", "José Berríos",
    "Shane Bieber", "Chris Sale", "Merrill Kelly", "Walker Buehler",
    "Yu Darvish", "Brandon Pfaadt", "Nestor Cortes", "Triston McKenzie",
    "Justin Verlander", "Gavin Williams", "Kyle Harrison", "Michael Wacha",
    "Yusei Kikuchi", "Eury Pérez", "Brayan Bello", "Braxton Garrett",
    "Clayton Kershaw", "Aaron Civale", "Eduardo Rodriguez",
    "Charlie Morton", "Joe Musgrove", "Cristopher Sánchez",
    "Kutter Crawford", "Luis Severino", "Jordan Montgomery",
}


def classify(name, closers, pitchers):
    if name in closers:
        return "CL"
    if name in pitchers:
        return "SP"
    if "(Batter)" in name or "(Pitcher)" in name:
        return "H" if "(Batter)" in name else "SP"
    return "H"


def parse_draft(text, closers, pitchers):
    """Parse a draft from copy-paste format."""
    picks = []
    current_round = 0
    for line in text.strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("Round "):
            current_round = int(line.split()[1])
            continue
        # Parse: "1.    Player Name    Team Name"
        parts = line.split("    ")
        parts = [p.strip() for p in parts if p.strip()]
        if len(parts) >= 3:
            pick_num = parts[0].rstrip(".")
            player = parts[1]
            team = parts[2]
            # Expand truncated team names
            team_map = {
                "Hart of the ...": "Hart of the Order",
                "Work in Prog...": "Work in Progress",
                "Tortured Bas...": "Tortured Baseball Department",
                "Boston Estre...": "Boston Estrellas",
                "Springfield ...": "Springfield Isotopes",
                "Crews Control": "Crews Control",
                "Jon's Underdogs": "Jon's Underdogs",
            }
            team = team_map.get(team, team)
            ptype = classify(player, closers, pitchers)
            picks.append({
                "round": current_round,
                "pick": int(pick_num),
                "player": player,
                "team": team,
                "type": ptype,
            })
    return picks


DRAFT_2025 = """Round 1
1.    Shohei Ohtani (Batter)    Work in Prog...
2.    Bobby Witt Jr.    Jon's Underdogs
3.    Aaron Judge    Spacemen
4.    Elly De La Cruz    Crews Control
5.    Corbin Carroll    Hello Peanuts!
6.    Juan Soto    Hart of the ...
7.    José Ramírez    Tortured Bas...
8.    Paul Skenes    Boston Estre...
9.    Kyle Tucker    SkeleThor
10.    Francisco Lindor    Springfield ...
Round 2
1.    Fernando Tatis Jr.    Springfield ...
2.    Gunnar Henderson    SkeleThor
3.    Tarik Skubal    Boston Estre...
4.    Vladimir Guerrero Jr.    Tortured Bas...
5.    Julio Rodríguez    Hart of the ...
6.    Jackson Chourio    Hello Peanuts!
7.    Yordan Alvarez    Crews Control
8.    Mookie Betts    Spacemen
9.    Zack Wheeler    Jon's Underdogs
10.    Trea Turner    Work in Prog...
Round 3
1.    Logan Gilbert    Work in Prog...
2.    Jarren Duran    Jon's Underdogs
3.    Bryce Harper    Spacemen
4.    Jazz Chisholm Jr.    Crews Control
5.    Garrett Crochet    Hello Peanuts!
6.    William Contreras    Hart of the ...
7.    Matt Olson    Tortured Bas...
8.    Jackson Merrill    Boston Estre...
9.    Freddie Freeman    SkeleThor
10.    Rafael Devers    Springfield ...
Round 4
1.    Ketel Marte    Springfield ...
2.    Corbin Burnes    SkeleThor
3.    Manny Machado    Boston Estre...
4.    Cole Ragans    Tortured Bas...
5.    Chris Sale    Hart of the ...
6.    Oneil Cruz    Hello Peanuts!
7.    Austin Riley    Crews Control
8.    Dylan Cease    Spacemen
9.    Pete Alonso    Jon's Underdogs
10.    Wyatt Langford    Work in Prog...
Round 5
1.    Jose Altuve    Work in Prog...
2.    Blake Snell    Jon's Underdogs
3.    Jacob deGrom    Spacemen
4.    Corey Seager    Crews Control
5.    Tyler Glasnow    Hello Peanuts!
6.    Emmanuel Clase    Hart of the ...
7.    Michael Harris II    Tortured Bas...
8.    Yoshinobu Yamamoto    Boston Estre...
9.    Ronald Acuña Jr.    SkeleThor
10.    Brent Rooker    Springfield ...
Round 6
1.    Teoscar Hernández    Springfield ...
2.    Ozzie Albies    SkeleThor
3.    Kyle Schwarber    Boston Estre...
4.    Devin Williams    Tortured Bas...
5.    CJ Abrams    Hart of the ...
6.    James Wood    Hello Peanuts!
7.    Framber Valdez    Crews Control
8.    Brenton Doyle    Spacemen
9.    Josh Hader    Jon's Underdogs
10.    Marcell Ozuna    Work in Prog...
Round 7
1.    Edwin Díaz    Work in Prog...
2.    Michael King    Jon's Underdogs
3.    Raisel Iglesias    Spacemen
4.    Mason Miller    Crews Control
5.    Spencer Schwellenbach    Hello Peanuts!
6.    Pablo López    Hart of the ...
7.    Shota Imanaga    Tortured Bas...
8.    Ryan Helsley    Boston Estre...
9.    Logan Webb    SkeleThor
10.    Aaron Nola    Springfield ...
Round 8
1.    Tanner Bibee    Springfield ...
2.    Lawrence Butler    SkeleThor
3.    Marcus Semien    Boston Estre...
4.    Bo Bichette    Tortured Bas...
5.    Junior Caminero    Hart of the ...
6.    Ryan Walker    Hello Peanuts!
7.    Alex Bregman    Crews Control
8.    Max Fried    Spacemen
9.    Félix Bautista    Jon's Underdogs
10.    Josh Naylor    Work in Prog...
Round 9
1.    Freddy Peralta    Work in Prog...
2.    Cody Bellinger    Jon's Underdogs
3.    Matt McLain    Spacemen
4.    Bailey Ober    Crews Control
5.    Andrés Muñoz    Hello Peanuts!
6.    Jhoan Duran    Hart of the ...
7.    Hunter Brown    Tortured Bas...
8.    Luis Castillo    Boston Estre...
9.    Anthony Santander    SkeleThor
10.    Riley Greene    Springfield ...
Round 10
1.    Seiya Suzuki    Springfield ...
2.    Adley Rutschman    SkeleThor
3.    Bryan Reynolds    Boston Estre...
4.    Joe Ryan    Tortured Bas...
5.    Bryce Miller    Hart of the ...
6.    Jordan Westburg    Hello Peanuts!
7.    Christian Walker    Crews Control
8.    Jake Burger    Spacemen
9.    Hunter Greene    Jon's Underdogs
10.    Mark Vientos    Work in Prog...
Round 11
1.    Roki Sasaki    Work in Prog...
2.    Willy Adames    Jon's Underdogs
3.    Mike Trout    Spacemen
4.    Zac Gallen    Crews Control
5.    Yainer Diaz    Hello Peanuts!
6.    Salvador Perez    Hart of the ...
7.    Cal Raleigh    Tortured Bas...
8.    Triston Casas    Boston Estre...
9.    George Kirby    SkeleThor
10.    Jeff Hoffman    Springfield ...
Round 12
1.    Alec Bohm    Springfield ...
2.    Spencer Strider    SkeleThor
3.    Sandy Alcantara    Boston Estre...
4.    Luis Robert Jr.    Tortured Bas...
5.    Robert Suarez    Hart of the ...
6.    Christian Yelich    Hello Peanuts!
7.    Justin Steele    Crews Control
8.    Willson Contreras    Spacemen
9.    Matt Chapman    Jon's Underdogs
10.    Will Smith    Work in Prog...
Round 13
1.    Sonny Gray    Work in Prog...
2.    Dylan Crews    Jon's Underdogs
3.    Tanner Scott    Spacemen
4.    Ian Happ    Crews Control
5.    Carlos Rodón    Hello Peanuts!
6.    Luis García Jr.    Hart of the ...
7.    Steven Kwan    Tortured Bas...
8.    Randy Arozarena    Boston Estre...
9.    Bryan Woo    SkeleThor
10.    Jack Flaherty    Springfield ...
Round 14
1.    Kevin Gausman    Springfield ...
2.    Trevor Megill    SkeleThor
3.    Xander Bogaerts    Boston Estre...
4.    Brice Turang    Tortured Bas...
5.    Pete Crow-Armstrong    Hart of the ...
6.    Cristopher Sánchez    Hello Peanuts!
7.    Brandon Nimmo    Crews Control
8.    Kodai Senga    Spacemen
9.    Luis Arraez    Jon's Underdogs
10.    Nick Castellanos    Work in Prog...
Round 15
1.    Vinnie Pasquantino    Work in Prog...
2.    J.T. Realmuto    Jon's Underdogs
3.    Ezequiel Tovar    Spacemen
4.    Josh Lowe    Crews Control
5.    Yandy Díaz    Hello Peanuts!
6.    Jasson Domínguez    Hart of the ...
7.    Adolis García    Tortured Bas...
8.    Jurickson Profar    Boston Estre...
9.    Xavier Edwards    SkeleThor
10.    Reynaldo López    Springfield ...
Round 16
1.    Seth Lugo    Springfield ...
2.    Ryan Pressly    SkeleThor
3.    Lane Thomas    Boston Estre...
4.    Robbie Ray    Tortured Bas...
5.    Shane McClanahan    Hart of the ...
6.    Kenley Jansen    Hello Peanuts!
7.    Shea Langeliers    Crews Control
8.    Eugenio Suárez    Spacemen
9.    Spencer Steer    Jon's Underdogs
10.    Nick Pivetta    Work in Prog...
Round 17
1.    Ryan Pepiot    Work in Prog...
2.    Pete Fairbanks    Jon's Underdogs
3.    Jordan Romano    Spacemen
4.    Andrés Giménez    Crews Control
5.    Michael Toglia    Hello Peanuts!
6.    Anthony Volpe    Hart of the ...
7.    Isaac Paredes    Tortured Bas...
8.    Austin Wells    Boston Estre...
9.    Jeremy Peña    SkeleThor
10.    Colton Cowser    Springfield ...
Round 18
1.    Jonathan India    Springfield ...
2.    Zach Eflin    SkeleThor
3.    Taj Bradley    Boston Estre...
4.    Brandon Pfaadt    Tortured Bas...
5.    Yusei Kikuchi    Hart of the ...
6.    Nolan Arenado    Hello Peanuts!
7.    Nathan Eovaldi    Crews Control
8.    Andrew Vaughn    Spacemen
9.    Tyler O'Neill    Jon's Underdogs
10.    Taylor Ward    Work in Prog...
Round 19
1.    Dansby Swanson    Work in Prog...
2.    Clay Holmes    Jon's Underdogs
3.    Jorge Soler    Spacemen
4.    David Bednar    Crews Control
5.    Josh Jung    Hello Peanuts!
6.    Bryson Stott    Hart of the ...
7.    Nico Hoerner    Tortured Bas...
8.    Carlos Estévez    Boston Estre...
9.    Kerry Carpenter    SkeleThor
10.    MacKenzie Gore    Springfield ...
Round 20
1.    Nick Lodolo    Springfield ...
2.    Tanner Houck    SkeleThor
3.    Jackson Holliday    Boston Estre...
4.    Heliot Ramos    Tortured Bas...
5.    Royce Lewis    Hart of the ...
6.    Max Scherzer    Hello Peanuts!
7.    Kyle Finnegan    Crews Control
8.    Mitch Keller    Spacemen
9.    Drew Rasmussen    Jon's Underdogs
10.    Paul Goldschmidt    Work in Prog...
Round 21
1.    Justin Martinez    Work in Prog...
2.    José Berríos    Jon's Underdogs
3.    Michael Wacha    Spacemen
4.    Spencer Arrighetti    Crews Control
5.    Ryan Mountcastle    Hello Peanuts!
6.    Gavin Williams    Hart of the ...
7.    Jesús Luzardo    Tortured Bas...
8.    Max Meyer    Boston Estre...
9.    Victor Robles    SkeleThor
10.    Willi Castro    Springfield ...
Round 22
1.    A.J. Puk    Springfield ...
2.    Cam Smith    SkeleThor
3.    Carlos Correa    Boston Estre...
4.    Masyn Winn    Tortured Bas...
5.    Tommy Edman    Hart of the ...
6.    Joey Ortiz    Hello Peanuts!
7.    Zach Neto    Crews Control
8.    Aroldis Chapman    Spacemen
9.    Shohei Ohtani (Pitcher)    Jon's Underdogs
10.    Logan O'Hoppe    Work in Prog...
Round 23
1.    Gleyber Torres    Work in Prog...
2.    Lourdes Gurriel Jr.    Jon's Underdogs
3.    Byron Buxton    Spacemen
4.    Cedric Mullins    Crews Control
5.    Rhys Hoskins    Hello Peanuts!
6.    Shane Baz    Hart of the ...
7.    Ronel Blanco    Tortured Bas...
8.    Jake McCarthy    Boston Estre...
9.    Jared Jones    SkeleThor
10.    Gabriel Moreno    Springfield ...
"""

DRAFT_2024 = """Round 1
1.    Julio Rodríguez    Hello Peanuts!
2.    Juan Soto    Hart of the ...
3.    Mookie Betts    Springfield ...
4.    Corbin Carroll    Boston Estre...
5.    Matt Olson    Crews Control
6.    Fernando Tatis Jr.    Jon's Underdogs
7.    Rafael Devers    Tortured Bas...
8.    Kyle Tucker    SkeleThor
9.    Bobby Witt Jr.    Spacemen
10.    Ronald Acuña Jr.    Work in Prog...
Round 2
1.    José Ramírez    Work in Prog...
2.    Corbin Burnes    Spacemen
3.    Shohei Ohtani (Batter)    SkeleThor
4.    Emmanuel Clase    Tortured Bas...
5.    Trea Turner    Jon's Underdogs
6.    Gerrit Cole    Crews Control
7.    Aaron Judge    Boston Estre...
8.    Austin Riley    Springfield ...
9.    Yordan Alvarez    Hart of the ...
10.    Spencer Strider    Hello Peanuts!
Round 3
1.    Adolis García    Hello Peanuts!
2.    Freddie Freeman    Hart of the ...
3.    Bo Bichette    Springfield ...
4.    Jose Altuve    Boston Estre...
5.    Marcus Semien    Crews Control
6.    Ozzie Albies    Jon's Underdogs
7.    Zac Gallen    Tortured Bas...
8.    Zack Wheeler    SkeleThor
9.    Luis Robert Jr.    Spacemen
10.    Michael Harris II    Work in Prog...
Round 4
1.    Bryce Harper    Work in Prog...
2.    Pete Alonso    Spacemen
3.    Francisco Lindor    SkeleThor
4.    Vladimir Guerrero Jr.    Tortured Bas...
5.    Corey Seager    SkeleThor
6.    Christian Yelich    Crews Control
7.    George Kirby    Boston Estre...
8.    Gunnar Henderson    Springfield ...
9.    Luis Castillo    Hart of the ...
10.    Tarik Skubal    Hello Peanuts!
Round 5
1.    Cody Bellinger    Hello Peanuts!
2.    CJ Abrams    Hart of the ...
3.    Randy Arozarena    Springfield ...
4.    Royce Lewis    Boston Estre...
5.    Logan Webb    Crews Control
6.    Yoshinobu Yamamoto    Jon's Underdogs
7.    Tyler Glasnow    Tortured Bas...
8.    Kevin Gausman    SkeleThor
9.    Pablo López    Spacemen
10.    Max Fried    Work in Prog...
Round 6
1.    Elly De La Cruz    Work in Prog...
2.    Manny Machado    Spacemen
3.    Framber Valdez    SkeleThor
4.    Aaron Nola    Tortured Bas...
5.    Freddy Peralta    Jon's Underdogs
6.    Edwin Díaz    Crews Control
7.    Mike Trout    Boston Estre...
8.    Logan Gilbert    Springfield ...
9.    Adley Rutschman    Hart of the ...
10.    Josh Hader    Hello Peanuts!
Round 7
1.    Oneil Cruz    Hello Peanuts!
2.    Grayson Rodriguez    Hart of the ...
3.    Bobby Miller    Springfield ...
4.    Blake Snell    Boston Estre...
5.    Zach Eflin    Crews Control
6.    Camilo Doval    Jon's Underdogs
7.    Nolan Jones    Tortured Bas...
8.    Paul Goldschmidt    SkeleThor
9.    Tanner Bibee    Spacemen
10.    Hunter Brown    Work in Prog...
Round 8
1.    Jazz Chisholm Jr.    Work in Prog...
2.    Raisel Iglesias    Spacemen
3.    Nolan Arenado    SkeleThor
4.    J.T. Realmuto    Tortured Bas...
5.    Kyle Schwarber    Jon's Underdogs
6.    Alex Bregman    Crews Control
7.    Evan Phillips    Boston Estre...
8.    Ha-Seong Kim    Springfield ...
9.    Joe Ryan    Hart of the ...
10.    Jesús Luzardo    Hello Peanuts!
Round 9
1.    Andrés Muñoz    Hello Peanuts!
2.    Alexis Díaz    Hart of the ...
3.    Spencer Steer    Springfield ...
4.    Triston Casas    Boston Estre...
5.    Nico Hoerner    Crews Control
6.    Will Smith    Jon's Underdogs
7.    Gleyber Torres    Tortured Bas...
8.    Cole Ragans    SkeleThor
9.    Evan Carter    Spacemen
10.    Yainer Diaz    Work in Prog...
Round 10
1.    Chris Bassitt    Work in Prog...
2.    Teoscar Hernández    Spacemen
3.    Christian Walker    Jon's Underdogs
4.    Nick Castellanos    Tortured Bas...
5.    Xander Bogaerts    Jon's Underdogs
6.    William Contreras    Crews Control
7.    Lane Thomas    Boston Estre...
8.    Dylan Cease    Springfield ...
9.    Justin Steele    Hart of the ...
10.    Bryson Stott    Hello Peanuts!
Round 11
1.    Riley Greene    Hello Peanuts!
2.    Ryan Helsley    Hart of the ...
3.    David Bednar    Springfield ...
4.    Clay Holmes    Boston Estre...
5.    George Springer    Crews Control
6.    Yandy Díaz    Jon's Underdogs
7.    Jordan Walker    Tortured Bas...
8.    Pete Fairbanks    SkeleThor
9.    Joe Musgrove    Spacemen
10.    Craig Kimbrel    Work in Prog...
Round 12
1.    --empty--    Work in Prog...
2.    Kenley Jansen    Spacemen
3.    Bryan Reynolds    SkeleThor
4.    Dansby Swanson    Tortured Bas...
5.    Shane Bieber    Jon's Underdogs
6.    Chris Sale    Crews Control
7.    Spencer Torkelson    Boston Estre...
8.    Paul Sewald    Springfield ...
9.    Ketel Marte    Hart of the ...
10.    Tanner Scott    Hello Peanuts!
Round 13
1.    Merrill Kelly    Hello Peanuts!
2.    Michael King    Hart of the ...
3.    Seiya Suzuki    Springfield ...
4.    Sonny Gray    Boston Estre...
5.    Marcell Ozuna    Crews Control
6.    Josh Jung    Jon's Underdogs
7.    Bailey Ober    Tortured Bas...
8.    Wyatt Langford    SkeleThor
9.    Zack Gelof    Spacemen
10.    Luis Arraez    Work in Prog...
Round 14
1.    Hunter Harvey    Work in Prog...
2.    Salvador Perez    Spacemen
3.    Andrés Giménez    SkeleThor
4.    Cedric Mullins    Tortured Bas...
5.    Walker Buehler    Jon's Underdogs
6.    Shota Imanaga    Crews Control
7.    Ryan Pepiot    Boston Estre...
8.    Jackson Chourio    Springfield ...
9.    Jordan Romano    Hart of the ...
10.    Sean Murphy    Hello Peanuts!
Round 15
1.    Kutter Crawford    Hello Peanuts!
2.    Alec Bohm    Hart of the ...
3.    Chas McCormick    Springfield ...
4.    Josh Naylor    Boston Estre...
5.    James Outman    Crews Control
6.    Masataka Yoshida    Jon's Underdogs
7.    Jorge Soler    Tortured Bas...
8.    Jhoan Duran    SkeleThor
9.    Hunter Greene    Spacemen
10.    Christian Encarnacion-Strand    Work in Prog...
Round 16
1.    Kerry Carpenter    Work in Prog...
2.    Mitch Keller    Spacemen
3.    Ian Happ    SkeleThor
4.    Anthony Santander    Tortured Bas...
5.    Yu Darvish    Jon's Underdogs
6.    José Alvarado    Crews Control
7.    Max Muncy    Boston Estre...
8.    Cristian Javier    Springfield ...
9.    Anthony Volpe    Hart of the ...
10.    Ezequiel Tovar    Hello Peanuts!
Round 17
1.    Ke'Bryan Hayes    Hello Peanuts!
2.    Vinnie Pasquantino    Hart of the ...
3.    Willson Contreras    Springfield ...
4.    Nick Pivetta    Boston Estre...
5.    Jonathan India    Crews Control
6.    Jarren Duran    Jon's Underdogs
7.    José Berríos    Tortured Bas...
8.    Josh Lowe    SkeleThor
9.    --empty--    Spacemen
10.    Nestor Cortes    Work in Prog...
Round 18
1.    Bryce Miller    Work in Prog...
2.    Willy Adames    Spacemen
3.    Cal Raleigh    SkeleThor
4.    Esteury Ruiz    Tortured Bas...
5.    Carlos Rodón    Jon's Underdogs
6.    Christopher Morel    Crews Control
7.    Francisco Alvarez    Boston Estre...
8.    Nathan Eovaldi    Springfield ...
9.    Brandon Nimmo    Hart of the ...
10.    Eloy Jiménez    Hello Peanuts!
Round 19
1.    Trevor Story    Hello Peanuts!
2.    Triston McKenzie    Hart of the ...
3.    Brandon Pfaadt    Springfield ...
4.    Alex Lange    Boston Estre...
5.    José Leclerc    Crews Control
6.    Robert Suarez    Jon's Underdogs
7.    Justin Verlander    Tortured Bas...
8.    Jordan Montgomery    SkeleThor
9.    Jake Burger    Spacemen
10.    Justin Turner    Work in Prog...
Round 20
1.    Brandon Drury    Work in Prog...
2.    Kyle Finnegan    Spacemen
3.    Charlie Morton    SkeleThor
4.    Thairo Estrada    Tortured Bas...
5.    Mason Miller    Jon's Underdogs
6.    Daulton Varsho    Crews Control
7.    Matt McLain    Boston Estre...
8.    Maikel Garcia    Springfield ...
9.    Nolan Gorman    Hart of the ...
10.    Edouard Julien    Hello Peanuts!
Round 21
1.    Jordan Westburg    Hello Peanuts!
2.    Steven Kwan    Hart of the ...
3.    Jack Suwinski    Springfield ...
4.    Gavin Williams    Boston Estre...
5.    Kyle Harrison    Crews Control
6.    Starling Marte    Jon's Underdogs
7.    Rhys Hoskins    Tortured Bas...
8.    Eduardo Rodriguez    SkeleThor
9.    Giancarlo Stanton    Spacemen
10.    Cristopher Sánchez    Work in Prog...
Round 22
1.    Michael Wacha    Work in Prog...
2.    Carlos Estévez    Spacemen
3.    Nathaniel Lowe    SkeleThor
4.    Aaron Civale    Tortured Bas...
5.    Jacob deGrom    Jon's Underdogs
6.    Isaac Paredes    Crews Control
7.    Tyler O'Neill    Boston Estre...
8.    Yusei Kikuchi    Springfield ...
9.    Taylor Ward    Hart of the ...
10.    Luis Severino    Hello Peanuts!
Round 23
1.    Ryan Mountcastle    Hello Peanuts!
2.    Eury Pérez    Hart of the ...
3.    Jackson Holliday    Springfield ...
4.    Brayan Bello    Boston Estre...
5.    Jonah Heim    Crews Control
6.    --empty--    Jon's Underdogs
7.    Braxton Garrett    Tortured Bas...
8.    Jeimer Candelario    SkeleThor
9.    Jorge Polanco    Spacemen
10.    Clayton Kershaw    Work in Prog...
"""


def analyze_team(picks, team_name):
    """Analyze a team's draft tendencies."""
    team_picks = [p for p in picks if p["team"] == team_name]
    sp_rounds = [p["round"] for p in team_picks if p["type"] == "SP"]
    cl_rounds = [p["round"] for p in team_picks if p["type"] == "CL"]
    h_rounds = [p["round"] for p in team_picks if p["type"] == "H"]

    first_sp = min(sp_rounds) if sp_rounds else None
    first_cl = min(cl_rounds) if cl_rounds else None
    early = [p for p in team_picks if p["round"] <= 5]
    early_h = sum(1 for p in early if p["type"] == "H")
    early_p = sum(1 for p in early if p["type"] in ("SP", "CL"))

    return {
        "total": len(team_picks),
        "hitters": len(h_rounds),
        "sp": len(sp_rounds),
        "closers": len(cl_rounds),
        "first_sp": first_sp,
        "first_cl": first_cl,
        "early_h": early_h,
        "early_p": early_p,
        "cl_rounds": cl_rounds,
        "sp_rounds": sp_rounds,
    }


def main():
    picks_2025 = parse_draft(DRAFT_2025, CLOSERS_2025, PITCHERS_2025)
    picks_2024 = parse_draft(DRAFT_2024, CLOSERS_2024, PITCHERS_2024)

    all_teams = set(p["team"] for p in picks_2025) | set(p["team"] for p in picks_2024)
    # Only analyze teams present in both years
    common = set(p["team"] for p in picks_2025) & set(p["team"] for p in picks_2024)

    print("=" * 90)
    print("OPPONENT DRAFT PROFILES (2024-2025)")
    print("=" * 90)

    for team in sorted(common):
        a25 = analyze_team(picks_2025, team)
        a24 = analyze_team(picks_2024, team)
        print(f"\n  {team}")
        print(f"  {'':4} {'Year':>5} {'H':>3} {'SP':>3} {'CL':>3}  {'1st SP':>6} {'1st CL':>6}  {'Early(R1-5)':>11}  CL rounds")
        print(f"  {'':4} {'2025':>5} {a25['hitters']:>3} {a25['sp']:>3} {a25['closers']:>3}  "
              f"{'R'+str(a25['first_sp']) if a25['first_sp'] else 'never':>6} "
              f"{'R'+str(a25['first_cl']) if a25['first_cl'] else 'never':>6}  "
              f"{a25['early_h']}H/{a25['early_p']}P{'':<5}  "
              f"{a25['cl_rounds']}")
        print(f"  {'':4} {'2024':>5} {a24['hitters']:>3} {a24['sp']:>3} {a24['closers']:>3}  "
              f"{'R'+str(a24['first_sp']) if a24['first_sp'] else 'never':>6} "
              f"{'R'+str(a24['first_cl']) if a24['first_cl'] else 'never':>6}  "
              f"{a24['early_h']}H/{a24['early_p']}P{'':<5}  "
              f"{a24['cl_rounds']}")

    # Closer demand curve
    print("\n" + "=" * 90)
    print("CLOSER DEMAND BY ROUND (both years combined)")
    print("=" * 90)
    from collections import Counter
    cl_by_round = Counter()
    for p in picks_2025 + picks_2024:
        if p["type"] == "CL":
            cl_by_round[p["round"]] += 1
    for rnd in range(1, 24):
        bar = "#" * cl_by_round.get(rnd, 0)
        if bar:
            print(f"  R{rnd:>2}: {bar} ({cl_by_round[rnd]})")

    # Summary profiles
    print("\n" + "=" * 90)
    print("STRATEGY CLASSIFICATION")
    print("=" * 90)
    for team in sorted(common):
        a25 = analyze_team(picks_2025, team)
        a24 = analyze_team(picks_2024, team)

        # Classify
        avg_first_cl = []
        if a25["first_cl"]: avg_first_cl.append(a25["first_cl"])
        if a24["first_cl"]: avg_first_cl.append(a24["first_cl"])
        avg_cl_round = sum(avg_first_cl) / len(avg_first_cl) if avg_first_cl else 99

        avg_first_sp = []
        if a25["first_sp"]: avg_first_sp.append(a25["first_sp"])
        if a24["first_sp"]: avg_first_sp.append(a24["first_sp"])
        avg_sp_round = sum(avg_first_sp) / len(avg_first_sp) if avg_first_sp else 99

        total_cl = a25["closers"] + a24["closers"]
        avg_early_h = (a25["early_h"] + a24["early_h"]) / 2

        if team == "Hart of the Order":
            label = "YOU — 3 closers, balanced approach"
        elif avg_cl_round <= 7 and total_cl >= 4:
            label = f"Closer-hungry (avg 1st closer R{avg_cl_round:.0f}, {total_cl} total)"
        elif avg_cl_round <= 9 and total_cl >= 2:
            label = f"Gets closers mid-draft (avg 1st closer R{avg_cl_round:.0f})"
        elif total_cl <= 1:
            label = f"Punt SV or late closer (avg 1st closer R{avg_cl_round:.0f})"
        elif avg_sp_round <= 3:
            label = f"Pitcher-first (avg 1st SP R{avg_sp_round:.0f})"
        elif avg_early_h >= 4:
            label = f"Hitter-heavy early ({avg_early_h:.0f} H in R1-5 avg)"
        else:
            label = "Balanced / mixed"

        print(f"  {team:<35} {label}")


if __name__ == "__main__":
    main()
